"""empty message

Revision ID: 890dd6fc4c2b
Revises: 
Create Date: 2024-01-04 00:31:05.055859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890dd6fc4c2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
